### ISSUE TITLE
Tags are not removed when editing a post

### ISSUE THREAD

**Issue by PhilipFlyvholm** [REXKrash/BDSA2021-ProjectBank#14]

**Comment by PhilipFlyvholm** [comment]
![image](https://user-images.githubusercontent.com/36300927/144818875-a7b3d7db-a077-41b0-96cf-bcbf9e296e99.png)
![image](https://user-images.githubusercontent.com/36300927/144818904-2dd64399-f079-4985-86ae-8ba5a3c9114a.png)
![image](https://user-images.githubusercontent.com/36300927/144818924-992a30b3-97b1-4712-9139-cf1b28ddbf9c.png)
![image](https://user-images.githubusercontent.com/36300927/144818942-74ad7e76-4b22-4305-9bfd-4ea907c9e065.png)

**Comment by REXKrash** [comment]
hello its finished
